export { default as About } from "./About"
export { default as Home } from "./Home"
export { default as MyContact } from "./MyContact"
export { default as HomeLayOut } from "./HomeLayOut"
// export { default as Github } from "./Github"
export { default as Resume } from "./Resume"